name: wombats
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3
  - pip
  - mkl
  - joblib
  - pygraphviz
  - python-graphviz
  - jupyter_contrib_nbextensions
  - ipywidgets
  - nbconvert
  - pip:
    - git+https://github.com/maximecb/gym-minigrid.git
    - -r requirements.txt

