name: wombats
channels:
  - defaults
  - conda-forge
dependencies:
  - joblib
  - jupyter_contrib_nbextensions
  - nbconvert
  - python=3
  - python-graphviz
  - pydot
  - matplotlib
  - scikit-learn
  - pip
  - scipy
  - networkx
  - bidict
  - pygraphviz
  - mkl
  - tqdm
  - ipywidgets
  - pandas
  - seaborn
  - pip:
    - git+https://github.com/maximecb/gym-minigrid.git
