# defines the final state probability needed for a state to be accepting
beta: 0.90

# number of symbols in pdfa alphabet
alphabetSize: 8

# number of states in pdfa state space
numStates: 3

# representation of the empty string / symbol (lambda if automata lit.)
lambdaTransitionSymbol: -1

# unique start state string label of pdfa
startState: 'q1'

# define a list of node labels, where each label is a string identifier label
# for a unique node, and the metadata properties for each node
nodes:

  'q0':
    final_probability: 0.89
    transDistribution: null
    isAccepting: null

  'q1':
    final_probability: 0.00
    transDistribution: null
    isAccepting: null

  'q2':
    final_probability: 1.00
    transDistribution: null
    isAccepting: null

# define the edges of the graph
edges:

  'q1':

    'q1':
      symbols:
        - 0
      probabilities:
        - 0.74

    'q0':
      symbols:
        - 4
      probabilities:
        - 0.20

    'q2':
      symbols:
        - 1
        - 2
        - 3
        - 5
        - 6
        - 7
      probabilities:
        - 0.01
        - 0.01
        - 0.01
        - 0.01
        - 0.01
        - 0.01

  'q0':

    'q0':
      symbols:
        - 4
      probabilities:
        - 0.05

    'q2':
      symbols:
        - 1
        - 2
        - 3
        - 5
        - 6
        - 7
      probabilities:
        - 0.01
        - 0.01
        - 0.01
        - 0.01
        - 0.01
        - 0.01

  'q2':